### ISSUE TITLE
''RemoteNavigationManager' has not been initialized.'

### ISSUE THREAD

**Issue by ErikApption** [jspuij/BlazorWebView#30] opened 2020-10-19 20:02 UTC
We are trying to convert our electron app to BlazorWebView and our index page and other components requires the NavigationManager. The app fails with the default "An unhandled error has occured" and when running with "Just My Code" disabled - we can see the following exception

`System.InvalidOperationException
  HResult=0x80131509
  Message='RemoteNavigationManager' has not been initialized.
  Source=Microsoft.AspNetCore.Components
  StackTrace:
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized() in /_/src/Components/Components/src/NavigationManager.cs:line 223`

Any suggestions?

**Comment by jspuij** [comment] 2020-11-09 14:26
duplicate of #31.

**Closed as completed by jspuij** 2020-11-09 14:26 UTC
